services:
  buidl-now:
    image: buidl-now:latest
    container_name: buidl-now
    restart: always
    env_file:
      - .env.production
    ports:
      - "3002:3000"
    networks:
      - buidl-now-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  buidl-now-network:
    name: buidl-now-network
    external: true
